### ISSUE TITLE
Bonjour sa serais bien dajouter le profil de la lotmaxx sc-10 pour klipper si possible 

### ISSUE THREAD

**Issue by Lucas5004** [tomsbasement/CheaPad#1]
Bonjour sa serais bien dajouter le profil de la lotmaxx sc-10 pour klipper si possible

**Comment by Lucas5004** [comment]
Bonjour sa serais bien dajouter le profil de la lotmaxx sc-10 pour klipper si possible

**Comment by bistory** [comment]
Hello, si tu trouves une configuration et que tu l'as testée, tu peux créer un pull request ;-)
