### ISSUE TITLE
Pb Accés btt-cb1.local

### ISSUE THREAD

**Issue by badjedi72** [tomsbasement/CheaPad#4]
Salut, 

super top cette video et ce cheapad tout a bien commencé .....je demarre le cheapad ok mais impossible d'accéder au serveur local de btt-cb1.local j'ai tout essayé avez vous une autre idée ou autre merci

**Comment by bistory** [comment]
Tu peux te connecter à son IP directement, tu peux obtenir cette info via les réglages réseau du pad ;-)
